all:
	gcc -Wall -Werror prog10.1.c -o prog10.1
	gcc -Wall -Werror prog10.2.c -o prog10.2
	gcc -Wall -Werror prog10.3.c -o prog10.3
	gcc -Wall -Werror prog10.4.c -o prog10.4
	gcc -Wall -Werror prog10.5.c -o prog10.5
	gcc -Wall -Werror prog10.6.c -o prog10.6
	gcc -Wall -Werror prog10.7.c -o prog10.7
	gcc -Wall -Werror prog10.8.c -o prog10.8
	gcc -Wall -Werror prog10.9.c -o prog10.9
	gcc -Wall -Werror prog10.10.c -o prog10.10
	gcc -Wall -Werror prog10.11.c -o prog10.11

clean:
	rm prog10.1 prog10.2 prog10.3 prog10.4 prog10.5 prog10.6 prog10.7 prog10.8 \
	prog10.9 prog10.10 prog10.11 
