all:
	gcc -Wall -Werror prog9.1.c -o prog9.1
	gcc -Wall -Werror prog9.2.c -o prog9.2
	gcc -Wall -Werror prog9.3.c -o prog9.3
	gcc -Wall -Werror prog9.4.c -o prog9.4
	gcc -Wall -Werror prog9.5.c -o prog9.5
	gcc -Wall -Werror prog9.6.c -o prog9.6
	gcc -Wall -Werror prog9.7.c -o prog9.7

clean:
	rm prog9.1 prog9.2 prog9.3 prog9.4 prog9.5 prog9.6 prog9.7 
