all:
	gcc -Wall -Werror prog18.1.c -o prog18.1
	gcc -Wall -Werror prog18.2.c -o prog18.2
	gcc -Wall -Werror prog18.3.c -o prog18.3
	gcc -Wall -Werror -g prog18.4.c -o prog18.4
	gcc -Wall -g prog18.5.c -o prog18.5

clean:
	rm prog18.1 prog18.2 prog18.3 prog18.4 prog18.5
