all:
	gcc -Wall -Werror prog4.1.c -o prog4.1
	gcc -Wall -Werror prog4.2.c -o prog4.2
	gcc -Wall -Werror prog4.3.c -o prog4.3
	gcc -Wall -Werror prog4.4.c -o prog4.4
	gcc -Wall -Werror prog4.5.c -o prog4.5

clean:
	rm prog4.1 prog4.2 prog4.3 prog4.4 prog4.5 
