all:
	gcc -Wall -Werror prog8.1.c -o prog8.1
	gcc -Wall -Werror prog8.2.c -o prog8.2
	gcc -Wall -Werror prog8.3.c -o prog8.3
	gcc -Wall -Werror prog8.4.c -o prog8.4
	gcc -Wall -Werror prog8.5.c -o prog8.5
	gcc -Wall -Werror prog8.6.c -o prog8.6
	gcc -Wall -Werror prog8.7.c -o prog8.7
	gcc -Wall -Werror prog8.8.c -o prog8.8
	gcc -Wall -Werror prog8.9.c -o prog8.9
	gcc -Wall -Werror prog8.10.c -o prog8.10
	gcc -Wall -Werror prog8.11.c -o prog8.11
	gcc -Wall -Werror prog8.12.c -o prog8.12
	gcc -Wall -Werror prog8.13.c -o prog8.13
	gcc -Wall -Werror prog8.13A.c -o prog8.13A
	gcc -Wall -Werror prog8.14.c -o prog8.14
	gcc -Wall -Werror prog8.15.c -o prog8.15
	gcc -Wall -Werror prog8.16.c -o prog8.16

clean:
	rm prog8.1 prog8.2 prog8.3 prog8.4 prog8.5 prog8.6 prog8.7 prog8.8 prog8.9 \
	prog8.10 prog8.11 prog8.12 prog8.13 prog8.13A prog8.14 prog8.15 prog8.16
