all:
	gcc -Wall -Werror e3.c -o e3
	gcc -Wall -Werror e4.c -o e4
	gcc -Wall -Werror e5.c -o e5
	gcc -Wall -Werror e6.c -o e6
	gcc -Wall -Werror e7.c -o e7
	gcc -Wall -Werror e8.c -o e8
	gcc -Wall -Werror e9.c -o e9
	gcc -Wall -Werror e11.c -o e11

clean:
	rm e3 e4 e5 e6 e7 e8 e9 e11
