all:
	gcc -Wall -Werror prog12.1.c -o prog12.1
	gcc -Wall -Werror prog12.2.c -o prog12.2
	gcc -Wall -Werror prog12.3.c -o prog12.3
	gcc -Wall -Werror prog12.4.c -o prog12.4

clean:
	rm prog12.1 prog12.2 prog12.3 prog12.4 
