all:
	gcc -Wall -Werror prog5.1.c -o prog5.1
	gcc -Wall -Werror prog5.2.c -o prog5.2
	gcc -Wall -Werror prog5.3.c -o prog5.3
	gcc -Wall -Werror prog5.3A.c -o prog5.3A
	gcc -Wall -Werror prog5.4.c -o prog5.4
	gcc -Wall -Werror prog5.5.c -o prog5.5
	gcc -Wall -Werror prog5.6.c -o prog5.6
	gcc -Wall -Werror prog5.7.c -o prog5.7
	gcc -Wall -Werror prog5.8.c -o prog5.8
	gcc -Wall -Werror prog5.9.c -o prog5.9

clean:
	rm prog5.1 prog5.2 prog5.3 prog5.3A prog5.4 prog5.5 prog5.6 prog5.7 \
	prog5.8 prog5.9
