all:
	gcc -Wall -Werror prog6.1.c -o prog6.1
	gcc -Wall -Werror prog6.2.c -o prog6.2
	gcc -Wall -Werror prog6.3.c -o prog6.3
	gcc -Wall -Werror prog6.4.c -o prog6.4
	gcc -Wall -Werror prog6.5.c -o prog6.5
	gcc -Wall -Werror prog6.6.c -o prog6.6
	gcc -Wall -Werror prog6.7.c -o prog6.7
	gcc -Wall -Werror prog6.8.c -o prog6.8
	gcc -Wall -Werror prog6.8A.c -o prog6.8A
	gcc -Wall -Werror prog6.9.c -o prog6.9
	gcc -Wall -Werror prog6.10.c -o prog6.10
	gcc -Wall -Werror prog6.10A.c -o prog6.10A

clean:
	rm prog6.1 prog6.2 prog6.3 prog6.4 prog6.5 prog6.6 prog6.7 prog6.8 prog6.9 \
	prog6.10 prog6.10A prog6.8A
