all:
	gcc -Wall -Werror e3.c -o e3
	gcc -Wall -Werror e4.c -o e4
	gcc -Wall -Werror e5.c -o e5
	gcc -Wall -Werror e6.c -o e6
	gcc -Wall -Werror e7.c -o e7
	gcc -Wall -Werror e8.c -o e8
	gcc -Wall -Werror e9.c -o e9
	gcc -Wall -Werror e10.c -o e10
	gcc -Wall -Werror e11.c -o e11
	gcc -Wall -Werror e12.c -o e12
	gcc -Wall -Werror e13.c -o e13
	gcc -Wall -Werror e14.c -o e14

clean:
	rm e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13 e14
