all:
	gcc -Wall -Werror prog3.1.c -o prog3.1
	gcc -Wall -Werror prog3.2.c -o prog3.2
	gcc -Wall -Werror prog3.3.c -o prog3.3
	gcc -Wall -Werror prog3.4.c -o prog3.4
	gcc -Wall -Werror prog3.5.c -o prog3.5
	gcc -Wall -Werror prog3.6.c -o prog3.6

clean:
	rm prog3.1 prog3.2 prog3.3 prog3.4 prog3.5 prog3.6
