all:
	gcc -Wall -Werror prog11.1.c -o prog11.1
	gcc -Wall -Werror prog11.2.c -o prog11.2
	gcc -Wall -Werror prog11.3.c -o prog11.3
	gcc -Wall -Werror prog11.4.c -o prog11.4
	gcc -Wall -Werror prog11.5.c -o prog11.5
	gcc -Wall -Werror prog11.6.c -o prog11.6
	gcc -Wall -Werror prog11.7.c -o prog11.7
	gcc -Wall -Werror prog11.8.c -o prog11.8
	gcc -Wall -Werror prog11.9.c -o prog11.9
	gcc -Wall -Werror prog11.10.c -o prog11.10
	gcc -Wall -Werror prog11.11.c -o prog11.11
	gcc -Wall -Werror prog11.12.c -o prog11.12
	gcc -Wall -Werror prog11.13.c -o prog11.13
	gcc -Wall -Werror prog11.14.c -o prog11.14
	gcc -Wall -Werror prog11.15.c -o prog11.15

clean:
	rm prog11.1 prog11.2 prog11.3 prog11.4 prog11.5 prog11.6 prog11.7 prog11.8 \
	prog11.9 prog11.10 prog11.11 prog11.12 prog11.13 prog11.14 prog11.15
