all:
	gcc -Wall -Werror prog7.1.c -o prog7.1
	gcc -Wall -Werror prog7.2.c -o prog7.2
	gcc -Wall -Werror prog7.3.c -o prog7.3
	gcc -Wall -Werror prog7.4.c -o prog7.4
	gcc -Wall -Werror prog7.5.c -o prog7.5
	gcc -Wall -Werror prog7.6.c -o prog7.6
	gcc -Wall -Werror prog7.7.c -o prog7.7
	gcc -Wall -Werror prog7.8.c -o prog7.8

clean:
	rm prog7.1 prog7.2 prog7.3 prog7.4 prog7.5 prog7.6 prog7.7 prog7.8 
