all:
	gcc -Wall -Werror e2.c -o e2
	gcc -Wall -Werror e3.c -o e3
	gcc -Wall -Werror e4.c -o e4
	gcc -Wall -Werror e5.c -o e5
	gcc -Wall -Werror e6.c -o e6
	gcc -Wall -Werror e7.c -o e7
	gcc -Wall -Werror e8.c -o e8
	gcc -Wall -Werror e9A.c -o e9A
	gcc -Wall -Werror e9B.c -o e9B
	gcc -Wall -Werror e9C.c -o e9C
	gcc -Wall -Werror e9D.c -o e9D
	gcc -Wall -Werror e9E.c -o e9E
	gcc -Wall -Werror e10.c -o e10
	gcc -Wall -Werror e10A.c -o e10A
	gcc -Wall -Werror e11.c -o e11

clean:
	rm e2 e3 e4 e5 e6 e7 e8 e9A e9B e9C e9D e9E e10 e10A e11
